### ISSUE TITLE
Why do all of these auth methods have data as a pramater?

### ISSUE THREAD

**Issue by CodeLuca** [CodeLuca/pudl#1]
These params are never even used?
http://cl.ly/image/0U0S0I08132H
@winghouchan

**Comment by CodeLuca** [comment]
This param needs to be changed to req and we need to pass the req object to it. Doing this now.

**Comment by winghouchan** [comment]
Agreed

On Fri, 6 Nov 2015, 11:32 Luca Marchal notifications@github.com wrote:

> This param needs to be changed to req and we need to pass the req object
> to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CodeLuca/pudl/issues/1#issuecomment-154388708.
> 
> ## 

Wing-Hou Chan

07946 629 450
winghouchan.co.uk
@winghouchan
in/winghouchan

**Comment by CodeLuca** [comment]
And it also needs res for redirecting, done this committing now.
